name: Add site-12 issues to project
on:
  issues:
    types:
      - opened
jobs:
  add-to-project:
    name: Add To GitHub projects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/UofTHacks-Official/projects/21
          github-token: ${{ secrets.GHPROJECT_TOKEN }}